################################################################################
# Filesystem hardening
################################################################################

# Extend FIFO protection to group-writable sticky directories.
fs.protected_fifos = 2

# Extend regular-file protection to group-writable sticky directories.
fs.protected_regular = 2