################################################################################
# Filesystem hardening
################################################################################
# the start of the file value is set to 60 so its not overwritten by default systemd configuration at 50

# Extend FIFO protection to group-writable sticky directories.
fs.protected_fifos = 2

# Extend regular-file protection to group-writable sticky directories.
fs.protected_regular = 2