# Failed-authentication policy

# Lock after five failed attempts within fifteen minutes
deny = 30
fail_interval = 900

# Automatically unlock after fifteen minutes
unlock_time = 900

# Avoid revealing whether an account exists
silent

# note for diploma: this should not be enabled as root should not be accessible via standard login and could
# create a denial of service if root is locked out.
#even_deny_root
#root_unlock_time = 900